### ISSUE TITLE
When press 'Steg' button

### ISSUE THREAD

**Issue by konarev** [mdbct/photocrypt#2]
photocrypt 

(photocrypt:9112): Gtk-CRITICAL **: gtk_text_buffer_emit_insert: assertion 'g_utf8_validate (text, len, NULL)' failed

(photocrypt:9112): Gtk-CRITICAL **: gtk_text_buffer_emit_insert: assertion 'g_utf8_validate (text, len, NULL)' failed
OpenCV Error: Unspecified error (could not find a writer for the specified extension) in imwrite_, file /build/opencv/src/opencv-2.4.10/modules/highgui/src/loadsave.cpp, line 275

(photocrypt:9112): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: /build/opencv/src/opencv-2.4.10/modules/highgui/src/loadsave.cpp:275: error: (-2) could not find a writer for the specified extension in function imwrite_

**Comment by munikarmanish** [comment]
The program seems to be working perfectly fine in my system. Can you help me reproduce the bug?

**Comment by konarev** [comment]
Okay. What information do you need?

**Comment by munikarmanish** [comment]
You may answer questions like these:
- How did u install this program?
- What is your system specifications?
- Did you get any warning (or unpossibly error) while installing or compiling?
- Have you tried stegging with different text and cover images?
- Does the CLI programs works?
- If you open the program (GUI) from the terminal, do you get any messages in the terminal?

You can include anything that might be helpful.

**Comment by konarev** [comment]
- my system:
  uname -a
  Linux arch-host 3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux
- install: yaourt photocrypt-git
- during installation there are no errors or warnings
- The application also falls with other data files
- cli application (steg and unsteg) working fine.

today re-assembled the application and run from command line.
After press 'Steg' button:

photocrypt 
OpenCV Error: Unspecified error (could not find a writer for the specified extension) in imwrite_, file /build/opencv/src/opencv-2.4.10/modules/highgui/src/loadsave.cpp, line 275

(photocrypt:3443): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: /build/opencv/src/opencv-2.4.10/modules/highgui/src/loadsave.cpp:275: error: (-2) could not find a writer for the specified extension in function imwrite_

**Comment by munikarmanish** [comment]
It seems there's something wrong in the gtkmm part (Since the CLI programs are working). Me and my friends are having no trouble running the application. You can suggest your friends to try it as well to see if it is really a program bug or something wrong in your system.

Also, have you tried compiling some other gtkmm or opencv programs to see if your opencv and gtkmm installations are clean.
